language: java

matrix:
    include:
    - name: java8
      jdk: openjdk8
      dist: xenial

    - name: java11
      jdk: openjdk11
      dist: bionic
    
    - name: java13
      jdk: openjdk11
      dist: bionic


after_success:
- mvn clean test jacoco:report coveralls:report
